//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TemplateUI.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("TemplateUI.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to  2.x,3.0.x,3.1.1,3.1.2,3.1.3,3.2.1,3.2.2,3.2.3,Premium 1.0.1,Premium 1.1.0,.
        /// </summary>
        internal static string Bridges {
            get {
                return ResourceManager.GetString("Bridges", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Titanium,Platinum,KaVo IXS,GXS-700,DEXcam 1-4,DEXcam 4HD,CariVu,3rd Party,.
        /// </summary>
        internal static string Devices {
            get {
                return ResourceManager.GetString("Devices", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 1.0.2,1.0.3,1.0.4,1.0.5,1.0.6,1.0.7,1.0.8,1.0.9,DTX Bridge,.
        /// </summary>
        internal static string Drivers {
            get {
                return ResourceManager.GetString("Drivers", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 9.0.x,9.1.x,9.2.x,9.3.x,9.4.0,9.4.1,9.4.2,9.4.3,9.4.4,9.4.5,9.4.6,9.4.8,9.4.9,9.5.0,10.0.x,10.1.0,10.1.1,10.1.2,10.1.3,10.1.6,11,DX Image,3rd Party,.
        /// </summary>
        internal static string Imaging {
            get {
                return ResourceManager.GetString("Imaging", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dentrix,Dentrix Ascend,Eaglesoft,Easy Dental,SoftDent,Practiceworks,OpenDental,AbelDent,.
        /// </summary>
        internal static string PMS {
            get {
                return ResourceManager.GetString("PMS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] RickRoll {
            get {
                object obj = ResourceManager.GetObject("RickRoll", resourceCulture);
                return ((byte[])(obj));
            }
        }
    }
}
